config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  devise_for :users
  resources :maps, only: [:index]
  resources :parkings, only: [:new, :create, :index, :show, :destroy] do
    resource :favorite, only:[:create, :destroy]
  end
  resources :users, only:[:show, :edit, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :parking
  
  validates :user_id, uniqueness: {scope: :parking_id}
end

app/models/parking.rb
class Parking < ApplicationRecord
  has_one_attached :parking_image
  belongs_to :user
  has_many :favorites, dependent: :destroy
  validates :spot_name, presence: true
  geocoded_by :address
  after_validation :geocode

  
  def get_parking_image(width, height)
    unless parking_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_parking.png')
      parking_image.attach(io: File.open(file_path), filename: 'no_image_parking.png', content_type: 'image/png')
    end
    parking_image.variant(resize_to_limit: [300, 300]).processed
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :parkings, dependent: :destroy
  has_many :favorites, dependent: :destroy

  has_one_attached :profile_image

  def get_profile_image(width, height)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image_human.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize_to_limit: [100, 100]).processed
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    parking = Parking.find(params[:parking_id])
    favorite = current_user.favorites.new(parking_id: parking.id)
    favorite.save
    redirect_to parking_path(parking)
  end
  
  def destroy
    parking = Parking.find(params[:parking_id])
    favorite = current_user.favorites.find_by(parking_id: parking.id)
    favorite.destroy
    redirect_to parking_path(parking)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  
  def top
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  def index
  end
end

app/controllers/parkings_controller.rb
class ParkingsController < ApplicationController

  def new
    @parking = Parking.new
  end

  def create
    @parking = Parking.new(parking_params)
    @parking.user_id = current_user.id
    if @parking.save
      flash[:notice] = "スポットを投稿していただきありがとうございます！"
      redirect_to parkings_path
    else
      render :new
    end
  end

  def index
    @parking = Parking.page(params[:page])
    @map = Parking.pluck(:user_id, :address, :latitude, :longitude)
  end

  def show
    @parking = Parking.find(params[:id])
    @user = @parking.user_id
  end

  def destroy
    parking = Parking.find(params[:id])
    if parking.destroy
      flash[:notice] = "スポットを削除しました！"
      redirect_to parkings_path
    else
      render :show
    end
  end

  private

  def parking_params
    params.require(:parking).permit(:spot_name, :address, :image, :caption, :latitude, :longitude)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @parking = @user.parkings
  end

  def edit
    @user = User.find(params[:id])
    unless @user.id == current_user.id
      redirect_to parkings_path
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集に成功しました！"
      redirect_to user_path(@user.id)
    else
      render :ender
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/parkings_helper.rb
module ParkingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/top.html.erb
<div>
  <div class = "main-visual">
    <div class="main-visual">
      <div class="main-visual-content">
        <p class="main-visual-text">
          Easy  Parking
        </p>
      </div>
    </div>
  </div>
  <div class="max-w-md mt-5">
    <div class="text-center">
      <h1 class="font-kaisei mb-3">EasyParkingとは</h1>
      <div class="text-base mx-auto">
        <p>　Easy Parkingは、初心者もしくは運転が苦手な人でも停めやすい駐車場や忙しい人でも事故を起こすことのない駐車場など</p>
        <p>簡単に停められる駐車場を投稿・共有する駐車場検索サービスです。</p>
      </div>
    </div>
    <div class="flex flex-wrap">
      <div class="mb-6 p-4 flex flex-col text-center items-center">
        <div class=" justify-center mb-5 ">
        </div>
        <div class="flex-grow">
          <h2 class="font-kaisei text-gray-900 text-lg title-font font-medium mb-3">こんな困りごとはありませんか？</h2>
          <p class="leading-relaxed text-base">　駐車が苦手でパーキングを探すのに苦労する。狭い駐車場で事故を起こしたくない。小さい子供がいるから広い駐車場がいい</p>
          <p class="leading-relaxed text-base">旅行先での駐車場が不安。一度狭い駐車場でぶつけたことがある。車体が大きいから余裕を持って駐車できれば、、、。etc.
        </div>
      </div>
      <div class="mb-6 p-4 flex flex-col text-center items-center">
        <div class="mb-5">
        </div>
        <div class="flex-grow">
          <h2 class="font-kaisei text-lg mb-3">その悩みを解決できたら？？</h2>
          <p class="leading-relaxed text-base text-gray-500"> 知らない土地でも駐車がしやすくなってノンストレス！！駐車場探しもカンタンに！</p>
        </div>
      </div>
      <div class="mb-6 p-4 flex flex-col text-center items-center">
        <div class="inline-flex items-center mb-5">
        </div>
        <div class="flex-grow">
          <h2 class="font-kaisei text-lg mb-3">早速ユーザー登録をしてパーキングの情報を共有しよう！！</h2>
          <p class="leading-relaxed text-base">　ユーザー登録を済ませたら、ページ下部の「投稿」ボタンから、あなたが見つけたお気に入りのスポットを投稿してみましょう。</p>
          <p>スポット情報の詳細を記入しみんなに共有することができます。</p>
        </div>
      </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Easy Park</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <script src="https://kit.fontawesome.com/60b0039113.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= javascript_pack_tag 'application' ,'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Kaushan+Script" rel="stylesheet">
    <%= favicon_link_tag('favicon.ico') %>
  </head>

  <body class = "d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class = "navbar">
            <a class = "navbar-brand p-3 ml-5" href = "/"><%= image_tag asset_path('Easy parking.png') %></a>
              <ul class="navbar-nav ml-auto list-group-horizontal">
                <% if user_signed_in? %>
                  <li class="nav-item">
                    <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark'  do %>
                      <i class="fa-solid fa-right-from-bracket fa-3x"></i><p>ログアウト</p>
                    <% end %>
                  </li>
                <% else %>
                  <li class="nav-item mr-5">
                    <%= link_to new_user_registration_path, class: 'text-dark' do %>
                    <i class="fa-solid fa-address-card fa-3x text-center"></i><p calss = "text-center">新規登録</p>
                    <% end %>
                  </li>
                  <li class="nav-item mx-5">
                    <%= link_to  new_user_session_path, class: 'text-dark'  do %>
                     <i class="fa-solid fa-right-to-bracket fa-3x text-center"></i><p calss = "text-center">ログイン</p>
                    <% end %>
                  </li>
                <% end %>
              </ul>
      </nav>
    </header>
  <main class="mb-auto">
    <div class = "message">
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </main>
    <footer class="pt-3 fixed-bottom">
          <nav class="">
            <div class = "container w-50">
              <ul class="navbar-nav", style="flex-direction: row;">
              <% if user_signed_in? %>
                <li class="col-3 text-center">
                  <%= link_to  root_path, class: 'text-dark'  do %>
                    <i class="fa-solid fa-house fa-2x text-center"></i><p calss = "text-center">ホーム</p>
                  <% end %>
                </li>
                <li class="col-3 text-center">
                  <%= link_to  parkings_path, class: 'text-dark'  do %>
                   <i class="fa-solid fa-magnifying-glass fa-2x text-center"></i><p calss = "text-center">検索</p>
                  <% end %>
                </li>
                <li class="col-3 text-center">
                  <%= link_to  user_path(current_user.id), class: 'text-dark'  do %>
                   <i class="fa-solid fa-user fa-2x text-center"></i><p calss = "text-center">マイページ</p>
                  <% end %>
                </li>
                <li class="col-3 text-center">
                  <%= link_to   new_parking_path, class: 'text-dark'  do %>
                   <i class="fa-solid fa-plus fa-2x text-center"></i><p calss = "text-center">投稿</p>
                  <% end %>
                </li>
              <% else %>
                <li class="col-3 text-center">
                  <%= link_to  root_path, class: 'text-dark'  do %>
                    <i class="fa-solid fa-house fa-3x text-center"></i><p calss = "text-center">ホーム</p>
                  <% end %>
                </li>
                <li class="col-3 text-center">
                  <%= link_to  new_user_session_path, class: 'text-dark'  do %>
                   <i class="fa-solid fa-magnifying-glass-plus fa-3x text-center"></i><p calss = "text-center">検索</p>
                  <% end %>
                </li>
                <li class="col-3 text-center">
                  <%= link_to  new_user_session_path, class: 'text-dark'  do %>
                   <i class="fa-solid fa-user fa-3x text-center"></i><p calss = "text-center">マイページ</p>
                  <% end %>
                </li>
                <li class="col-3 text-center">
                  <%= link_to  new_user_session_path, class: 'text-dark'  do %>
                   <i class="fa-solid fa-plus fa-3x text-center"></i><p calss = "text-center">投稿</p>
                  <% end %>
                </li>
              <% end %>
              </ul>
            </div>
          </nav>
      </div>
    </footer>
  </body>
</html>

app/views/parkings/index.html.erb
   <div class="card-list-container w-50 py-5 mx-auto mb-5">
      <% @parking.each do |parking| %>
      <div class="card w-75 mx-auto mt-4 shadow-lg">
        <div class="card-body">
          <div class="row mx-auto">
            <div class="col-lg-4 col-sm-12 mx-auto text-center">
              <%= image_tag parking.user.get_profile_image(100,100), class: "mt-3 rounded-circle"; %>
              <p><i class="fas fa-user"><%= parking.user.name %></i><p>
            </div>
            <div class="col-lg-7 col-sm-12">
              <p class="card-title">
                 <%= link_to(parking_path(parking.id), class: "text-dark") do %>
                  <strong><i class="far fa-flag"></i><span><%= parking.spot_name %></span></strong></br>
                  <%= parking.address %>
                <% end %>
              </p>
              <p class="card-text"><strong>どんな駐車場？</strong></br><%= parking.caption %></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
    <div class = "text-center">
      <%= paginate @parking %>
    </div>
<div class = "container">
  <div class = "row">
    <div class = "col-12 text-center">
      <h2>地図検索</h2>
    </div>
  </div>
  <div class = "row mb-3">
    <div class = "col-12 text-center">
      <input id="address" type="textbo" placeholder = "住所・探したい地名で検索">
      <input type="button" value="検索" onclick="codeAddress()">
    </div>
  </div>
  <div class = "row mx-auto">
    <div class = "col-12">
      <div id='map'></div>

      <style>
      #map {
        height: 600px;
        width: 600px;
        margin: 0 auto;
        margin-bottom: 30px;
      }
      </style>

      <script>
        let map

        function initMap() {
          geocoder = new google.maps.Geocoder()

          map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: 35.6809591, lng:139.7673068},
            zoom: 15,
          });

          marker = new google.maps.Marker({
            position:  {lat: 35.6809591, lng:139.7673068},
            map: map
          });

          <% @parking.each do |parking|%>
            ( function() {
              let markerLatLng = { lat: <%= parking.latitude %>, lng: <%= parking.longitude %> }; // 緯度経度のデータ作成
              let marker = new google.maps.Marker({
                position: markerLatLng,
                map: map
              });
              let infowindow = new google.maps.InfoWindow({
                position: markerLatLng,
                content: "<a href='<%= parking_url(parking.id) %>' target='_blank'><%= parking.address %></a>"
              }); //ここで詳細ページへのリンクを表示させる
              marker.addListener('click', function() {
                infowindow.open(map, marker);
              });

             })();
          <% end %>
        }
        let geocoder

        function codeAddress(){
          let inputAddress = document.getElementById('address').value;

          geocoder.geocode( { 'address': inputAddress}, function(results, status) {
            if (status == 'OK') {
              map.setCenter(results[0].geometry.location);
              var marker = new google.maps.Marker({
                  map: map,
                  position: results[0].geometry.location
              });
            } else {
              alert('該当する結果がありませんでした：' + status);
            }
          });
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api_key %>&callback=initMap" async defer></script>
    </div>
  </div>
</div>

app/views/parkings/new.html.erb
<div class = "container mx-auto pt-5 flex justify-center aligun-center">
  <h1 class = "col-6 col-sm-12 mx-auto font-bold pt-5 text-center">New パーキング</h1>
  <% if @parking.errors.any? %>
    <div class = "col-6 col-sm-12 mx-auto">
      <%= @parking.errors.count %>件のエラーが発生しました
      <ul>
        <% @parking.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "col-6 mx-auto pt-3">
    <%= form_with model: @parking do |f| %>
      <div class = "mb-1">
        <div class = "pt-5 pb-1">
          <label for = "spot_name">スポット名</label>
        </div>
          <%= f.text_field :spot_name, class: "form-control", id: "spot_name" %>
      </div>
      <div class = "mb-1">
        <div class = "pt-5 pb-1">
          <label for = "address">住所</label>
        </div>
          <%= f.text_field :address, class: "form-control", id: "address" %>
      </div>
      <div class = "mb-1">
        <div class = "pt-5 pb-1">
          <label for = "caption">どんな駐車場？</label>
        </div>
          <%= f.text_area :caption, class: "form-control", id: "caption" %>
      </div>
      <div class = "mb-1">
        <div class = "pt-5 pb-1">
          <label for = "image">写真</label>
        </div>
        <div class = "btn">
           <%= f.file_field :parking_image, accept: "image/*", id: "image"%>
        </div>
      </div>
      <div class = "pb-5 justify-center align-center">
        <div class = "text-center pt-5">
          <%= f.submit '     投稿    ', class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/parkings/show.html.erb
<div class = "container w-50 mx-auto pt-5 px-5 flex justify-center aligun-center">
  <div class = "row-sm-6 pt-5 pb-2">
    <div class = "flex inline-flex hover:underline">
      <%= link_to parkings_path do %>
        <p class = "mr-2">⬅️<span>戻る</span></p>
      <% end %>
    </div>
  </div>
  <div class = "row border-bottom border-dark flex justify-center aligun-center">
    <div class = "col-sm-6">
      <p class = "pl-2 mx-auto"><strong><i class="far fa-flag mr-2"></i><span><%= @parking.spot_name %></span></strong>
    </div>
    <div class = "col-sm-6 text-right">
      <% if @parking.favorited_by?(current_user) %>
        <p>
          <%= link_to parking_favorite_path(@parking), method: :delete do %>
            ♥️<%= @parking.favorites.count %>
          <% end %>
        </p>
      <% else %>
        <p>
          <%= link_to parking_favorite_path(@parking), method: :post do %>
            ♡<%= @parking.favorites.count %>
          <% end %>
        </p>
      <% end %>
    </div>
  </div>
  <div class = "row border-bottom border-dark mt-2">
    <div class = "col-12">
      <p><strong>住所</strong></p>
      <p></p><%= @parking.address %></p>
    </div>
    <div class = "col-12 center-block mb-5">
      <div id="map"></div>
      <style>
      #map {
        height: 500px;
        width: 500px;
        margin: 0 auto;
        margin-bottom: 30px;
      }
      </style>


      <script>
        function initMap(){
          // 地図の位置情報(緯度・経度)を取得
          let mapPosition = {lat: <%= @parking.latitude %> , lng: <%= @parking.longitude %> };
          let map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: mapPosition
          });
          let transitLayer = new google.maps.TransitLayer();
          transitLayer.setMap(map);

          let contentString = '【住所】<%= @parking.address %>';
          let infowindow = new google.maps.InfoWindow({
            content: contentString
          });

          let marker = new google.maps.Marker({
            position: mapPosition,
            map: map,
            title: contentString
          });

          marker.addListener('click', function(){
            infowindow.open(map, marker);
          });
        }
      </script>
      <script src="https://maps.googleapis.com/maps/api/js?key=<%= Rails.application.credentials.google_map_api_key %>&callback=initMap" async defer></script>
  </div>
  </div>
  <div class = "row border-bottom border-dark mt-2">
    <div class = "col-12">
      <p><strong>どんな駐車場？</strong></p>
      <p></p><%= @parking.caption %></p>
    </div>
  </div>
  <div class = "row border-bottom border-dark mt-2">
    <div class = "col-12">
      <p><strong>投稿画像</strong></p>
      <div class = "img-container text-center">
        <p><%= image_tag @parking.get_parking_image(300, 300) %></p>
      </div>
    </div>
  </div>
  <div class = "row pb-5">
    <div class = "col-12">
      <p><strong>投稿日</strong>：<%= @parking.created_at.strftime('%Y/%m/%d') %></p>
    </div>
  </div>
  <div class = "row pb-5">
    <div class = "col-12">
      <div class = "text-center d-grid gap-2 d-md-block">
        <% if @parking.user == current_user %>
          <%= link_to "  削除  ", parking_path(@parking), method: :delete, class: "btn btn-primary" %>
        <% end %>
      </div>
    </div>
  </div>

</div>

app/views/users/edit.html.erb
<div class = "container mx-auto pt-5 flex justify-center aligun-center">
  <h1 class = "col-6 col-sm-12 mx-auto font-bold pt-5 text-center">プロフィール編集</h1>
  <% if @user.errors.any? %>
    <div class = "col-6 col-sm-12 mx-auto">
      <%= @user.errors.count %>件のエラーが発生しました
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "col-6 mx-auto pt-3">
    <%= form_with model: @user do |f| %>
      <div class = "mb-1">
        <div class = "pt-5 pb-1">
          <label for = "name">名前</label>
        </div>
          <%= f.text_field :name, class: "form-control", id: "name" %>
      </div>
      <div class = "mb-1">
        <div class = "pt-5 pb-1">
          <label for = "email">メールアドレス</label>
          <%= f.email_field :email, class: "form-control", id: "email" %>
        </div>
      </div>
      <div class = "mb-1">
        <div class = "pt-5 pb-1">
          <label for = "image">アバター</label>
        </div>
        <div class = "btn">
           <%= f.file_field :profile_image, accept: "image/*", id: "image"%>
        </div>
      </div>
      <div class = "mb-1">
        <div class = "pt-2 pb-3">
          <%= image_tag @user.get_profile_image(100,100), class: "d-block rounded-circle img-fluid"; %>
        </div>
      </div>
      <div class = "pb-5 text-center">
        <div class = "pt-4">
          <%= f.submit "編集", class: "btn btn-primary" %>
        </div>
      </div>
    <% end %>
</div>

app/views/users/show.html.erb
<!-- ユーザー詳細 -->
<div class = "container mx-auto pt-5 flex justify-center aligun-center">
  <div class="row mx-auto pl-5 mx-auto pt-5 flex justify-center aligun-center border-bottom border-dark">
        <div class="col-5">
              <%= image_tag @user.get_profile_image(100,100), class: "d-block float-right mt-3  rounded-circle img-fluid"; %>
        </div>
        <div class = "col-7">
          <p class = "mt-4"><i class="fas fa-user"><%= @user.name %></i></br><%= @user.email %><p>
          <% if @user == current_user %>
            <%= link_to "   編集   ", edit_user_path(@user), class: "btn btn-info btn-sm " %>
          <% end %>
        </div>
  </div>
</div>

<!-- ユーザー投稿一覧 -->

   <div class="card-list-container w-75 mx-auto py-5">
      <% @parking.each do |parking| %>
        <div class="card w-50 mx-auto mt-4 shadow-lg">
          <%= link_to parking_path(parking.id) do %>
  
          <% end %>
          <div class="card-body col-8 mx-auto">
                <p class="card-title">
                   <%= link_to(parking_path(parking.id), class: "text-dark") do %>
                    <strong><i class="far fa-flag"></i><span><%= parking.spot_name %></span></strong></br>
                    <%= parking.address %>
                  <% end %>
                </p>
                <p class="card-text"><strong>どんな駐車場？</strong></br><%= parking.caption %></p>
            </div>
        </div>
      <% end %>
    </div>